name: Run NestJS Crawler

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t video:latest -f Dockerfile .

      - name: Run container
        run: |
          docker run --rm \
            -e NODE_ENV=production \
            -e TZ=Asia/Taipei \
            -e PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
            -e CHROMIUN_BROWSER_PATH=/usr/bin/chromium-browser \
            -p 3000:3000 \
            video:latest
